### ISSUE TITLE
在i-row组件上添加view，然后给view绑定事件，会报错

### ISSUE THREAD

**Issue by JinGangRed** [TalkingData/iview-weapp#115]
我的情况是这样的，使用栅格布局后，我希望在<i-row>标签上添加一个点击事件，i-row没有事件的属性，于是，我准备使用view标签将i-row包裹起来，然后在view上添加时间，当添加完事件之后，发现开发工具报错。当我单独定义一个view标签后，再绑定事件，发现是没有问题的。代码如下：
` <view bindtap='showDetailInfo'>
    <i-row i-class="sub_header" >
      <i-col span="3" i-class="label">
        现价
      </i-col>
      <i-col span="8" i-class="price">
        180
      </i-col>
    </i-row>
</view>
`
JS中的代码如下：
`/**
   * 显示详情
   */
  showDetailInfo:function(event){
    console.log(event);
  }`

开发工具报错如下：
`TypeError: Cannot read property 'offsetLeft' of undefined
    at g (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:20:3614)
    at o.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:20:4734)
    at r.safeCallback (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:5:28158)
    at r.call (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:5:27922)
    at n (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:5:30388)
    at http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:5:30942
    at s (http://127.0.0.1:49710/__pageframe__/__dev__/WAWebview.js:5:29956)
    at Function.r.dispatchEvent (`
请帮忙解决一下是什么问题

**Comment by ShariseMo** [comment]
我也遇到同样的问题，请问解决了吗？

**Comment by ShariseMo** [comment]
在i-row上绑定事件，或者包裹住iview组件的view绑定点击事件都有这个错误
