### ISSUE TITLE
when i npm install

### ISSUE THREAD

**Issue by Fnckerpoi** [TalkingData/iview-weapp#298]
iview-weapp@2.0.0 prepare C:\Users\Administrator\Desktop\iview-weapp
> npm run build

> iview-weapp@2.0.0 build C:\Users\Administrator\Desktop\iview-weapp
> gulp --gulpfile build/build-prod.js

[12:51:06] Working directory changed to ~\Desktop\iview-weapp\build
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (C:\Users\Administrator\Desktop\iview-weapp\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\Administrator\Desktop\iview-weapp\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\iview-weapp\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-weapp@2.0.0 build: `gulp --gulpfile build/build-prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-weapp@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-20T04_51_06_420Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-weapp@2.0.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-weapp@2.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-20T04_51_06_502Z-debug.log

**Comment by MulderLiu** [comment]
我也是同样错误，楼主有解决了吗

**Comment by xiaodongjava** [comment]
> iview-weapp@2.0.0 prepare C:\Users\Administrator\Desktop\iview-weapp
> 
> > npm run build
> 
> > iview-weapp@2.0.0 build C:\Users\Administrator\Desktop\iview-weapp
> > gulp --gulpfile build/build-prod.js
> 
> [12:51:06] Working directory changed to ~\Desktop\iview-weapp\build
> fs.js:25
> 'use strict';
> ^
> 
> ReferenceError: internalBinding is not defined
> at fs.js:25:1
> at req_ (C:\Users\Administrator\Desktop\iview-weapp\node_modules\natives\index.js:137:5)
> at Object.req [as require] (C:\Users\Administrator\Desktop\iview-weapp\node_modules\natives\index.js:54:10)
> at Object. (C:\Users\Administrator\Desktop\iview-weapp\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:99)
> at Module._compile (internal/modules/cjs/loader.js:721:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
> at Module.load (internal/modules/cjs/loader.js:620:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
> at Function.Module._load (internal/modules/cjs/loader.js:552:3)
> at Module.require (internal/modules/cjs/loader.js:657:17)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! iview-weapp@2.0.0 build: `gulp --gulpfile build/build-prod.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the iview-weapp@2.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2019-01-20T04_51_06_420Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! iview-weapp@2.0.0 prepare: `npm run build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the iview-weapp@2.0.0 prepare script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2019-01-20T04_51_06_502Z-debug.log

你需要修改  natives 版本 试试     npm install natives@1.1.6

**Comment by xiaodongjava** [comment]
> 我也是同样错误，楼主有解决了吗

你需要修改 natives 版本 试试 npm install natives@1.1.6   然后 再运行 npm install

**Comment by CarGod** [comment]
> > 我也是同样错误，楼主有解决了吗
> 
> 你需要修改 natives 版本 试试 npm install natives@1.1.6 然后 再运行 npm install

这个方法可以

**Comment by OneFreeCoder** [comment]
还有其他方法吗，搞了几天都没找到答案
